project:
  type: website
  output-dir: docs

website:
  title: "BIO228 at CCNY"
  navbar:
    background: info
    search: true
    right:
      - href: index.qmd
        text: Home
      - text: R Labs
        menu:
          - ./labs/lab06.qmd
          - ./labs/lab7-comm_eco/lab7.qmd
          - ./labs/lab12.qmd
          - ./labs/lab13.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual